version: "3.8"
services:
  backend:
    image: pybaseimage
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pybase_web_backend
    ports:
      - "8448:80"
    healthcheck:
      test: curl --fail http://127.0.0.1 || exit 1
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 20s
    restart: unless-stopped
  db:
    image: postgres
    container_name: pybase_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pybase
      POSTGRES_PASSWORD: 6pqnhbtEqGAfA6Rj34tUCN43oCEcKKLaHXWZM70wzM40HDdJ7WmdKVTEN4mMIJNL1HiYeToA2WkaBF1cmRZcyQWuFtTNjpyRe7Se
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pybase_pgadmin4
    restart: always
    ports:
      - "8889:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pybase.internal
      PGADMIN_DEFAULT_PASSWORD: 6pqnhbtEqGAfA6Rj34tUCN43oCEcKKLaHXWZM70wzM40HDdJ7WmdKVTEN4mMIJNL1HiYeToA2WkaBF1cmRZcyQWuFtTNjpyRe7Se
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: